from kruskal import *

print("="*16, "Inicio", "="*16)
g = Grafo(False)

vA = Vertice("a")
g.addVert(vA)
vB = Vertice("b")
g.addVert(vB)
vC = Vertice("c")
g.addVert(vC)
vD = Vertice("d")
g.addVert(vD)
vE = Vertice("e")
g.addVert(vE)
vF = Vertice("f")
g.addVert(vF)
vG = Vertice("g")
g.addVert(vG)
vH = Vertice("h")
g.addVert(vH)
vI = Vertice("i")
g.addVert(vI)

print("="*40)

a0 = Aresta(vA, vB, 4)
g.addAresta(a0)
a1 = Aresta(vA, vC, 8)
g.addAresta(a1)
a2 = Aresta(vB, vC, 11)
g.addAresta(a2)
a3 = Aresta(vB, vE, 8)
g.addAresta(a3)
a4 = Aresta(vC, vD, 9)
g.addAresta(a4)
a5 = Aresta(vC, vI, 6)
g.addAresta(a5)
a6 = Aresta(vD, vE, 7)
g.addAresta(a6)
a7 = Aresta(vD, vI, 14)
g.addAresta(a7)
a8 = Aresta(vE, vF, 7)
g.addAresta(a8)
a9 = Aresta(vE, vH, 5)
g.addAresta(a9)
a10 = Aresta(vF, vG, 10)
g.addAresta(a10)
a11 = Aresta(vF, vH, 12)
g.addAresta(a11)
a12 = Aresta(vG, vH, 11)
g.addAresta(a12)
a13 = Aresta(vH, vI, 7)
g.addAresta(a13)

print("="*40)

print("Arvore geradora minima: ", g.KruskalAnimado())

print("="*40)
